from typing import Protocol
from uuid import UUID

from osca.instrument.api import InstrumentReference, ProviderMapping


class InstrumentRepository(Protocol):
    def add_instrument(self, instrument: InstrumentReference) -> None: ...
    def get_instrument(self, instrument_id: UUID) -> InstrumentReference | None: ...
    def find_by_identity(self, identity_key: tuple[str, ...]) -> InstrumentReference | None: ...
    def add_mapping(self, mapping: ProviderMapping) -> None: ...
    def mappings_for_alias(self, mapping: ProviderMapping) -> tuple[ProviderMapping, ...]: ...
